name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libcriterion-dev

      - name: Build and install the library
        run: |
          # Create the local lib directory for building before installing
          mkdir -p lib
          make OPTION=test
          sudo make install

      - name: Build and run tests
        run: make OPTION=test run_test
